-- docs/sql/intraday_signals.sql
-- 本表用於紀錄盤中即時觸發的訊號 (I-1 大單, I-2 爆量, I-3 急拉, I-4 發動)
-- 搭配 docs/24 盤中訊號雷達架構使用

CREATE TABLE public.intraday_signals (
    id bigint generated by default as identity primary key,
    stock_id text not null,
    stock_name text not null,
    signal_type text not null, -- 'I-1', 'I-2', 'I-3', 'I-4'
    signal_desc text,
    price numeric,
    volume bigint,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.intraday_signals ENABLE ROW LEVEL SECURITY;

-- 允許登入用戶唯讀
CREATE POLICY "Allow authenticated read intraday_signals"
ON public.intraday_signals FOR SELECT
TO authenticated
USING (true);

-- 本機 Worker 使用 Service Key，將會自動 Bypass RLS，無需特別定義寫入 Policy

-------------------------------------------------------------------------------

-- 紀錄 Worker 是否活著的 Heartbeat 表
CREATE TABLE public.worker_heartbeat (
    id int primary key default 1,
    status text not null, -- 'online', 'offline'
    last_active_at timestamp with time zone default timezone('utc'::text, now()) not null,
    CONSTRAINT single_row CHECK (id = 1)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.worker_heartbeat ENABLE ROW LEVEL SECURITY;

-- 允許登入用戶唯讀
CREATE POLICY "Allow authenticated read worker_heartbeat"
ON public.worker_heartbeat FOR SELECT
TO authenticated
USING (true);
